-- Analytics events table for first-party tracking
create table if not exists public.logs_analytics (
  id bigint generated by default as identity primary key,
  owner_id uuid,                 -- nullable for anonymous page views
  type text not null,
  payload jsonb,
  created_at timestamptz default now()
);
alter table public.logs_analytics enable row level security;

-- Anyone can insert their own events; nobody can select (admin-only later if needed)
create policy "analytics_insert" on public.logs_analytics for insert
  with check (auth.uid() = owner_id or owner_id is null);
create policy "analytics_no_select" on public.logs_analytics for select
  using (false);

